### ISSUE TITLE
The XML checking of the compliance checker does not validate the schema

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica-tools/FMUComplianceChecker#25]
**Reported by sjoelund&#46;se on 19 Jan 2017 12:43 UTC**
Currently, if you try to upload an FMU containing:
```xml
<ModelStructure>
  <Outputs>
  </Outputs>
```
this is rejected by the post-commit hook with a cryptic error message. This is due to failing to validate the XML schema (xsd files). The fmuChecker happily accepts the FMU though, and it works in all importing tools I have encountered. It would be good if FMIL could validate the schema.

----

Migrated-From: https://trac.fmi-standard.org/ticket/404

**Comment by filip-stenstrom** [comment]
This issue seems to have two parts to it:

1. An example that shows a bug
2. A general statement (see title) that XML schema validation through XSD should be done

Since (1) shows an example with a missing end-tag, which is handled, I believe that something went missing with the issue transfer from trac. I'm closing this ticket, but please re-open if you know the complete example.

For (2), today all validation is done through FMI Library at parse time. An extended solution is to also use some other tool for the schema validation. That's out of scope for this issue though.

**Comment by beutlich** [comment]
@sjoelund FYI
